### ISSUE TITLE
No icon on FlatHUb !

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.github.taiko2k.tauonmb#2]
Hi. I detected that there is no icon for your application in FlatHub when viewed from within a category - see attached screenshot bellow (blue arrow):

![icons](https://user-images.githubusercontent.com/25375330/103275935-272f7400-49bd-11eb-8c8c-6934d69beea6.png)

**Comment by Taiko2k** [comment]
Seems to be a Flathub issue. A report relating to this has been opened here https://github.com/flathub/backend/issues/24

**Comment by Taiko2k** [comment]
Fixed now.
